---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k3s-pool
  namespace: metallb
spec:
  addresses:
  - 10.1.50.128/25

---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: ff-icr01
  namespace: metallb
spec:
  myASN: 65101
  peerASN: 65001
  peerAddress: 10.1.80.1
  bfdProfile: bfdprofile
