---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb

resources:
  - bgpConfiguration.yml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/metallb
  prune: true
  wait: true
