apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBF0FoxQnKxDmwhm5KzelIzBNrB+8ajCK8J4nmeroQdEbhAmPWKXJbPXVVC8Uv78Km6jTEd1VdoL4qYz/MprjpZ7DmiouZ/xycojJXesFVHyNA/xcRA9R2J5pJ1ruw070l/UadJoGtPHCB52BmoEkmMB02KXL+7kuc3xs7xl0D4g/Zpt3Eajveri03gAgOEyrZXV24cwXr0oobd7qY530NyT0WhWu2rGIb3x2JPyqv+eZNAlGT+i5nM101ujNC8qjYFZwet8hHtnfcOT13nxZ4rBvz3F35CW+w/sby54xy5bERJo1f12eJUYchs4NDyBZM0cOfdNN2OzG0IWeZ7rKwZswVrHRjQm9xFk63AHswh9q9Pfa2U8uR7OPVKNy8gFoeDOmKXVxsnw7eYVDSqVOuz4/RMwQcmodRr+sDSFl6w7OMPEa1IkYij1uKWZTzKFDb4ZOpKdrHDoXs6vhOMHvuQmhtgeBTydOhRK9OOLQBdX5dhD2qOKFwcJhgDYbIUnlTEjbqejzX/QAcTyI+6IQD51Fqv9wO5TzF9uItItygYUSF6upNCrOXg/emm0d0GEin1cM+PilI0S54nypHcbkx2EIt+nBSZOkwwERbS+f8nzH9JowWc67b0ZvakYrwmWjGCCiWegXjVZuhzIjYC4IqdWedZkhD/7k17/NccUypvICCHWkvnBJOZj11Y2RG0Ofv4HxIRZRi3GJLDnitG7BLS+NAoYEy9tBXOjpkA7wE9Db6eMpO/3WZ1
  template:
    metadata:
      creationTimestamp: null
      name: cf-api-token-secret
      namespace: cert-manager
    type: Opaque

# kubeseal --format=yaml --cert=/Users/ryanb/Documents/Documents\ -\ Ryan\'s\ Laptop/iCloud/keys/k3sdev-sealed-secrets/pub-sealed-secrets.pem  < secrets.yml > sealedsecrets.yml --controller-namespace sealed-secrets