---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 24h
  url: https://bitnami-labs.github.io/sealed-secrets

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace