apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgACwEuH16qwSOmUfzoeQyC91A3A9loiisjH7wSuLbWaoctGganJR+Xv7KeVPpkufq4ACLDDl4vYBImw/uIGzEvl/pXLdUjBbVqy4rxKaFkXapbs9K756EY3HAL8zxE68KFdCjzdgOJ7c9W8Y5oeWZODPfiMpuOmU0NZaM3Plg9jVlxLXLGhiY2VUDbUxbPylbsXAJ9WTRqrT/QndT1AnzTRRAViL7HvpbnkaGWW+inbVj/B5TkztDeyHDAM0+q2ylHisuP6zSa56UPK58VKd8AGisZy6RYNs9UX0bhN2JmKhKaF8FayZSVCFXYE/qDy9CGiu4WitwCdRySRQbzCw0H9pg2eom2PuCPDPKno6dRYF9buXiS+xUqByqxpaFhv3ZaOhE6dtNkeaOjSVZuFghEOrrR5rHNJJOPhlWaRklzv6f9r2JT98R4iVYfwx+fPaWRWdGnuWX0cWUCCTM01nuadHxljULlUR/UhrtyRECq0bUZRUA1tw4fAorr4RRqGasI4LVbT1wSzhyKO5S3G5NiILb62Gj17yIh5u0ZuGlbZvao/CmuNFa9dCTL40FoUdhdX73kXuowuGEkrFr2Hr58qg9xex5/4dJaC1km7WaWPqgl8UPmAr9nyCtP1aRC0iOAFyKVXkSKM1/IIanxg1nbKTYbKnLHaZDWCX+O4hhQTl3OONs69AKSYK0ece67pEO9uRt33SaGvxQJNdhz1jO2k1o5ZX7/iI8GlywjgdRjj0Y/xGz4+SMMMZenzIwFa8s7Y+GUjSD7OrPoMkBs=
    username: AgCMOhv500DCIhPb/+Gc0efeiWzTysplgXHSuITAS2jZZ+XYT5rcakmFSdza37XtQKXAVbejvRFQz6YirYorVgDwRmaMsarHrKN2dOeq/56S6dQCXDTHRPfL4A5dSKhmbyBjP5q2TUziRZrN4LOdoHXJh7M3xCl8GH/kVoLan3J3DTKuutMgLyO5dZMieUP7WnPKWscLLUyQHyhKfn4T4cn5Z5euf79dPi+F1S1Xpp/jrPqMO99Af6fNZpyqn9gaykd3lz6HuZa2tM5UxAAZmOx40VEe0g9Q9TJoV+v/dBRA1YJ8eafaryFgu1JLzuTs2sKZNpessQZ5ik2TiXi+LPrJEcXxG+SSBV42sbGWcWbbo83K46MM8Mu0YgEk+yiiSunCuGt8ykHDkFXC9WtxESBOVdPo6cgEEEK1ky8a6TVapAg1ALNsw0eVOFS9kczNEl4oBStGwgNgI10XYBauHmrgr6tskUTjkOavGlXHh2WO8PIPQ4qQhFXWqqK1rfAvSwwmEtyLfD+0ZnFewCUoVA30lq1DVHUirryTVK91LNKDlnLg/ikaua4+Ue2AvDIQ5QSi9v3tvR7xjTQQWmLfcohhIi0/h5Wf+EcPAYLGqVuWvZMDH1k60QNVC2JOOdhG6kYmse+Uk1xEMGcFd5tfYhGXmYt8SIC7cclTDKry14Rrw7fHe3tBA36OObDoU+YXMxqgbsFywQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque

