apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/cert-manager

patches:
  - path: cert-manager-values.yml
    target:
      kind: ClusterIssuer
      name: letsencrypt
